apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-svc
  name: blue-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web-port
    nodePort: 30080
  selector:
    app: blue-deployment
  type: NodePort
status:
  loadBalancer: {}
