apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: green-svc
  name: green-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web-port
    nodePort: 30081
  selector:
    app: green-deployment
  type: NodePort
status:
  loadBalancer: {}
