apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blue-deployment
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-deployment
    spec:
      containers:
      - image: ydamle/images:blueapp
        name: blue
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          #name: web-port
        resources: {}
status: {}
