apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green-deployment
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green-deployment
    spec:
      containers:
      - image: ydamle/images:greenapp
        name: green
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web-port
        resources: {}
status: {}

-----------